export const GET_CHAT_REQUEST = 'GET_CHAT_REQUEST'
export const GET_CHAT_SUCCESS = 'GET_CHAT_SUCCESS'
export const GET_CHAT_FAIL = 'GET_CHAT_FAIL'

export const SEND_MSG_REQUEST = 'SEND_MSG_REQUEST'
export const SEND_MSG_SUCCESS = 'SEND_MSG_SUCCESS'
export const SEND_MSG_FAIL = 'SEND_MSG_FAIL'

export const GET_STACK_REQUEST = 'GET_STACK_REQUEST'
export const GET_STACK_SUCCESS = 'GET_STACK_SUCCESS'
export const GET_STACK_FAIL = 'GET_STACK_FAIL'
