export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_LOGOUT = 'USER_LOGOUT'

export const GET_LOGIN_USER_REQUEST = 'GET_LOGIN_USER_REQUEST'
export const GET_LOGIN_USER_SUCCESS = 'GET_LOGIN_USER_SUCCESS'
export const GET_LOGIN_USER_FAIL = 'GET_LOGIN_USER_FAIL'

export const SEARCH_USER_REQUEST = 'SEARCH_USER_REQUEST'
export const SEARCH_USER_SUCCESS = 'SEARCH_USER_SUCCESS'
export const SEARCH_USER_FAIL = 'SEARCH_USER_FAIL'
export const SEARCH_USER_RESET = 'SEARCH_USER_RESET'

export const CONNECTION_USER_REQUEST = 'CONNECTION_USER_REQUEST'
export const CONNECTION_USER_SUCCESS = 'CONNECTION_USER_SUCCESS'
export const CONNECTION_USER_FAIL = 'CONNECTION_USER_FAIL'

export const CANCEL_CONNECTION_USER_REQUEST = 'CANCEL_CONNECTION_USER_REQUEST'
export const CANCEL_CONNECTION_USER_SUCCESS = 'CANCEL_CONNECTION_USER_SUCCESS'
export const CANCEL_CONNECTION_USER_FAIL = 'CANCEL_CONNECTION_USER_FAIL'

export const GET_PENDING_REQUEST = 'GET_PENDING_REQUEST'
export const GET_PENDING_SUCCESS = 'GET_PENDING_SUCCESS'
export const GET_PENDING_FAIL = 'GET_PENDING_FAIL'

export const ACCEPT_FRIEND_REQUEST = 'ACCEPT_FRIEND_REQUEST'
export const ACCEPT_FRIEND_SUCCESS = 'ACCEPT_FRIEND_SUCCESS'
export const ACCEPT_FRIEND_FAIL = 'ACCEPT_FRIEND_FAIL'
